"""Create obstetric models with updated fields

Revision ID: 6a86589c2b05
Revises: 
Create Date: 2026-01-11 22:27:39.479186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a86589c2b05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_cases',
    sa.Column('id_caso', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del caso'),
    sa.Column('edad_materna', sa.Integer(), nullable=False, comment='Edad de la madre en años'),
    sa.Column('paridad', sa.Integer(), nullable=False, comment='Número de embarazos previos'),
    sa.Column('controles_prenatales', sa.Integer(), nullable=False, comment='Número de controles prenatales realizados'),
    sa.Column('semanas_gestacion', sa.Float(), nullable=False, comment='Semanas de gestación (puede incluir decimales)'),
    sa.Column('hipertension_previa', sa.Integer(), nullable=False, comment='Historial de hipertensión (0: No, 1: Sí)'),
    sa.Column('diabetes_gestacional', sa.Integer(), nullable=False, comment='Diagnóstico de diabetes gestacional (0: No, 1: Sí)'),
    sa.Column('cesarea_previa', sa.Integer(), nullable=False, comment='Cesárea previa (0: No, 1: Sí)'),
    sa.Column('embarazo_multiple', sa.Integer(), nullable=False, comment='Embarazo múltiple (0: No, 1: Sí)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id_caso')
    )
    op.create_index(op.f('ix_patient_cases_id_caso'), 'patient_cases', ['id_caso'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_case_id', sa.Integer(), nullable=False),
    sa.Column('riesgo_sepsis', sa.Integer(), nullable=True, comment='Predicción de riesgo de sepsis (0: Bajo, 1: Medio, 2: Alto)'),
    sa.Column('riesgo_hipertension_gestacional', sa.Integer(), nullable=True, comment='Predicción de riesgo de hipertensión gestacional (0: Bajo, 1: Medio, 2: Alto)'),
    sa.Column('riesgo_hemorragia_posparto', sa.Integer(), nullable=True, comment='Predicción de riesgo de hemorragia posparto (0: Bajo, 1: Medio, 2: Alto)'),
    sa.Column('probabilidad_sepsis', sa.Float(), nullable=True),
    sa.Column('probabilidad_hipertension', sa.Float(), nullable=True),
    sa.Column('probabilidad_hemorragia', sa.Float(), nullable=True),
    sa.Column('modelo_version', sa.String(), nullable=True, comment='Versión del modelo utilizado'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Fecha de la predicción'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_predictions_id'), 'risk_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_risk_predictions_patient_case_id'), 'risk_predictions', ['patient_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_predictions_patient_case_id'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_id'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_patient_cases_id_caso'), table_name='patient_cases')
    op.drop_table('patient_cases')
    # ### end Alembic commands ###
